export const businessDefaultConfig = (businessId: number) => {
    return [
        //Generals
        {
            key: "order_notification_users",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "allowed_roles_to_allow_reentry",
            value: "ADMIN,OWNER",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "disable_reentry_in_business",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "maximum_day_working_hours",
            value: "12",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_multiple_person_selection_production_areas",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enforced_a_commission",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_notifications_in_tablet",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enforce_business_open_close",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "business_startsat_working_hours",
            value: "06",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "business_endsat_working_hours",
            value: "17",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "transfer_orders_to_next_economic_cycle",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "force_access_system",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_pick_up_in_store",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_notifications_in_tablet",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "transform_invoice_into_sell_currency",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_to_sale_in_negative",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "general_cost_currency",
            value: "CUP",
            businessId: businessId,
            isSensitive: false,
        },
        //Billing
        {
            key: "billing_show_customer_data",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "billing_show_business_data",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "billing_show_business_logo",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "billing_print_force_currency",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "billing_print_force_currency_defined",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        //Tickets printed
        {
            key: "ticket_print_barcode",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "ticket_business_name",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "print_minified_ticket",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "ticket_footer",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "ticket_print_all_data_client",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "ticket_print_allow_to_pay_in_other_currencies",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "ticket_print_unitary_price",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "ticket_print_logo",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_print_ticket_via_lan",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "printer_configurations_lan",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        //POS
        {
            key: "show_cash_operations_in_tablet",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "show_cash_report_in_tablet",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "limit_number_order_billed_in_tablet",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "amount_order_to_show_billed_in_tablet",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "payment_methods_enabled",
            value: "CASH,TRANSFER",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "payment_methods_enabled",
            value: "CASH,TRANSFER",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enabled_discounts",
            value: "100,75,50,25,10",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "show_pos_transfer_online_orders",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "default_method_payment",
            value: "CASH",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "print_number_order",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "print_hours_in_order",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "type_products",
            value: "MENU,STOCK,RAW,MANUFACTURED,ADDON,COMBO",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_ongoing_orders",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "open_cashbox_at_print",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "cash_operations_include_tips",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "cash_operations_include_deliveries",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "extract_salary_from_cash",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "calculate_salary_from",
            value: "TOTAL_SALES", //"GROSS_REVENUE"
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "allow_to_cancel_orders",
            value: "MANAGER_SALES,MANAGER_SHIFT,ADMIN,OWNER",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "allow_discounts",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "allow_commission",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enabled_commissions",
            value: "50,25,10",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "only_products_ready_for_sale",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "unify_categories_stock_sale",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "pos_allow_pending_payment",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "generate_ticket_for_production_in_fast_orders",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "block_production_ticket_to_return",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        //Tecopay
        {
            key: "tecopay_target_account",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "tecopay_registered_data",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        //Delivery
        {
            key: "enable_pick_up_in_store",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_delivery",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "delivery_type",
            value: "FIXED", //FIXED,VARIABLE,BYREGION
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "minimun_amount_to_buy_with_delivery",
            value: "{}",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "amount_delivery_fixed",
            value: "0",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "is-economiccycle-automated",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "economiccycle-startAt",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "economiccycle-endsAt",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "open_economicCycle_with_priceSystemId",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "show-menu-in-pos",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_oficial_exchange_rate",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "return_order_change_according_oficial_exchange",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "print_order_with_prices_adjust_to_oficial_exchange",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        //Stocks
        //Options -> FIFO, FEFO
        {
            key: "algoritm_to_manage_batchs",
            value: "FIFO",
            businessId: businessId,
            isSensitive: false,
        },
        {
            //To make elaborations directo in stock area - role: MANAGER_AREA ++
            key: "allow_tablet_to_elaborate_products_in_stock",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            //To make operations of adjust or movements - role: MANAGER_AREA, MANAGER_SALES ++
            key: "allow_tablet_to_make_direct_operations_in_stock",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            //To make operations of adjust or movements - role: MANAGER_AREA, PRODUCT_PROCESATOR ++
            key: "allow_tablet_to_make_fast_entries_in_stock",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            //To precission in cost, supplies y quantities in stock (Tecnichal cart)
            key: "precission_after_coma",
            value: "4",
            businessId: businessId,
            isSensitive: false,
        },
        {
            //To make operations of movements translate - role: MANAGER_AREA ++
            key: "allow_tablet_to_make_movements_in_stock",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            //To make operations of translations - role: MANAGER_AREA ++
            key: "allow_tablet_to_make_transformations_in_stock",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "allow_to_make_dispatch_from_sale",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "shifts_management",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "show_revenue_in_tablet",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "show_coupons_in_tablet",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        //Bill invoice
        {
            key: "invoice_business_name",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "invoice_header",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "invoice_observations",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "force_consecutive_invoice_numbers",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        //Modules
        {
            key: "module_accounts",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "module_duplicator",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "duplicator_businessId",
            value: "",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "module_woocommerce",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "module_production",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "module_human_resources",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "module_billing",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "module_booking",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        //Aplicaciones móviles
        {
            key: "android_min_version",
            value: "1.0.0",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "android_url_store",
            value: "",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "ios_min_version",
            value: "1.0.0",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "ios_url_store",
            value: "",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "is_app_in_manteinance",
            value: "false",
            businessId: businessId,
            isSensitive: true,
        },
        //Shop
        {
            key: "currencies_for_sale_exchange_rate",
            value: "CUP",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "enable_sale_shop_multiple_currencies_from_exchange_rate",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "online_shop_main_currency",
            value: "USD",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "online_shop_price_system",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "online_shop_area_stock",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "online_shop_enable_cancel_orders_automatically",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "online_shop_cancel_order_after_X_hours",
            value: "",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "when_shop_create_preorder",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "online_shop_show_current_currency_modal",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "create_order_in_status",
            value: "PAYMENT_PENDING",
            businessId: businessId,
            isSensitive: false,
        },
        //Options: ORDER_CREATED, ORDER_BILLED
        {
            key: "substract_from_inventory_at",
            value: "ORDER_CREATED",
            businessId: businessId,
            isSensitive: false,
        },
        //Visuals
        {
            key: "visual_online_shop",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "visual_suppliers",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "visual_customers",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "visual_economic_cycles",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "visual_dispatches",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "visual_batch",
            value: "false",
            businessId: businessId,
            isSensitive: false,
        },
        {
            key: "visual_human_resources",
            value: "true",
            businessId: businessId,
            isSensitive: false,
        },
        //Tropipay
        {
            key: "tropipay_client_id",
            value: "",
            businessId: businessId,
            isSensitive: true,
        },
        {
            key: "tropipay_client_secret",
            value: "",
            businessId: businessId,
            isSensitive: true,
        },
    ];
};
